steps:
  - name: 'gcr.io/cloud-builders/docker@sha256:19e157ad231ad8f006f47d653b6c931997c49e107f28dd73d72bfb09d0a5691e'
    args:
      [
        'build',
        '-t',
        'gcr.io/$PROJECT_ID/pc-form-generator:$SHORT_SHA',
        '-t',
        'gcr.io/$PROJECT_ID/pc-form-generator:latest',
        '-f',
        'Dockerfile',
        '.',
      ]
  - name: 'gcr.io/cloud-builders/docker@sha256:19e157ad231ad8f006f47d653b6c931997c49e107f28dd73d72bfb09d0a5691e'
    args: ['push', 'gcr.io/$PROJECT_ID/pc-form-generator:$SHORT_SHA']
  - name: 'gcr.io/cloud-builders/gcloud@sha256:a7f5211b196655817644f95cc66b1f9fed57fccd3d886e18b638c853d14b4978'
    args: 
      [
        'beta', 
        'run', 
        'deploy', 
        'pc-form-generator',
        '--image', 
        'gcr.io/$PROJECT_ID/pc-form-generator:$SHORT_SHA',
        '--region', 
        'us-central1',
        '--allow-unauthenticated',
        '--platform',
        'managed' 
      ]
images:
  - 'gcr.io/$PROJECT_ID/pc-form-generator:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/pc-form-generator:latest'
  