steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'gcr.io/$PROJECT_ID/pc-form-generator:$SHORT_SHA',
        '-t',
        'gcr.io/$PROJECT_ID/pc-form-generator:latest',
        '-f',
        'Dockerfile',
        '.',
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/pc-form-generator:$SHORT_SHA']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: 
      [
        'beta', 
        'run', 
        'deploy', 
        'pc-form-generator',
        '--image', 
        'gcr.io/$PROJECT_ID/pc-form-generator:$SHORT_SHA',
        '--region', 
        'us-central1',
        '--allow-unauthenticated',
        '--platform',
        'managed' 
      ]
images:
  - 'gcr.io/$PROJECT_ID/pc-form-generator:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/pc-form-generator:latest'
  