name: "Terraform Apply Production"

on:
  push:
    branches:
      - main
    paths:
      - "terragrunt/**"
      - ".github/workflows/tf_apply_production.yml"

env:
  AWS_REGION: ca-central-1
  TERRAFORM_VERSION: 1.3.9
  TERRAGRUNT_VERSION: 0.44.4
  CONFTEST_VERSION: 0.27.0
  TF_VAR_cloudfront_header: ${{ secrets.CLOUDFRONT_HEADER }}

permissions:
  id-token: write
  contents: read
  pull-requests: write
  actions: write
  checks: write
  statuses: write
  
jobs:
  terragrunt-apply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3.0.2

      - name: setup terraform tools
        uses: cds-snc/terraform-tools-setup@v1

      - name: configure aws credentials using OIDC
        uses: aws-actions/configure-aws-credentials@8c3f20df09ac63af7b3ae3d7c91f105f857d8497 # v4.0.0
        with:
          role-to-assume: arn:aws:iam::414662622316:role/simplify-privacy-statements-V2-apply
          role-session-name: TFApply
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Apply ECR
        working-directory: terragrunt/env/production/ecr
        run: terragrunt apply --terragrunt-non-interactive -auto-approve

      - name: Terraform Apply VPC
        working-directory: terragrunt/env/production/vpc
        run: terragrunt apply --terragrunt-non-interactive -auto-approve

      - name: Terraform Apply EFS
        working-directory: terragrunt/env/production/efs
        run: terragrunt apply --terragrunt-non-interactive -auto-approve

      - name: Terraform Apply Lambda
        working-directory: terragrunt/env/production/app
        run: terragrunt apply --terragrunt-non-interactive -auto-approve

      - name: Terraform Apply Hosted Zone
        working-directory: terragrunt/env/production/hosted_zone
        run: terragrunt apply --terragrunt-non-interactive -auto-approve

      - name: Terraform Apply Cloudfront
        working-directory: terragrunt/env/production/cloudfront
        run: terragrunt apply --terragrunt-non-interactive -auto-approve    
