name: "Terraform Plan"

on:
  workflow_dispatch:
  pull_request:
    paths:
    - "terragrunt/**"
    - ".github/workflows/tf_plan_production.yml"
    
env:
  AWS_REGION: ca-central-1
  TERRAFORM_VERSION: 1.3.9
  TERRAGRUNT_VERSION: 0.44.4
  CONFTEST_VERSION: 0.27.0
  TF_VAR_cloudfront_header: ${{ secrets.CLOUDFRONT_HEADER }}

permissions:
  id-token: write
  contents: read
  pull-requests: write
  actions: write
  checks: write
  statuses: write
  
jobs:
  terragrunt-plan:
    strategy:
      matrix:
        include:
          - module: ecr
          - module: efs
          - module: vpc
          - module: app
          - module: hosted_zone
          - module: cloudfront
          
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - name: setup terraform tools
        uses: cds-snc/terraform-tools-setup@v1

      - name: configure aws credentials using OIDC
        uses: aws-actions/configure-aws-credentials@8c3f20df09ac63af7b3ae3d7c91f105f857d8497 # v4.0.0
        with:
          role-to-assume: arn:aws:iam::414662622316:role/simplify-privacy-statements-V2-plan
          role-session-name: TFPlan
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform plan
        uses: cds-snc/terraform-plan@8be66db9c815352044405fd33120b91918bf1f2e # v2.3.1
        with:
          comment-delete: true
          comment-title: "Production: ${{ matrix.module }}"
          directory: terragrunt/env/production/${{ matrix.module }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          terragrunt: true            